//.cpp æ–‡ä»¶, å¾€ä¸‹æ·»åŠ 
#include "MainPlayer.h" 
#include "GameFramework/SpringArmComponent.h" //å¼•å…¥æ‚¬è‡‚è·Ÿæ‘„åƒæœºçš„å¤´æ–‡ä»¶ã€2ã€‘
#include "Camera/CameraComponent.h" //å¼•å…¥æ‚¬è‡‚è·Ÿæ‘„åƒæœºçš„å¤´æ–‡ä»¶ã€2ã€‘
#include "Components/CapsuleComponent.h" //å¼•å…¥èƒ¶å›Šä½“çš„å¤´æ–‡ä»¶ã€3ã€‘
#include "Components/InputComponent.h" //å¼•å…¥è½´äº‹ä»¶çš„å¤´æ–‡ä»¶ã€4ã€‘
#include "GameFramework/PlayerController.h" //å¼•å…¥ Controller çš„å¤´æ–‡ä»¶ã€5ã€‘
#include "GameFramework/CharacterMovementComponent.h" //å¼•å…¥ Character çš„å¤´æ–‡ä»¶ã€6ã€‘


// æ„é€ å‡½æ•°, å¯¹ç»„ä»¶è¿›è¡Œåˆå§‹åŒ– â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
AMainPlayer::AMainPlayer() { 
	PrimaryActorTick.bCanEverTick = true;

	//å®ä¾‹åŒ– SpringArm - ğŸ— æ‘„åƒæœºæ‚¬è‡‚ 
	SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm")); //æ ¹æ® USpringArmComponent ç±»åˆ›å»ºå®ä¾‹
	SpringArm -> SetupAttachment(GetRootComponent()); //å°†ã€æ‚¬è‡‚ã€‘é™„ç€åˆ°ã€æ ¹ç»„ä»¶ã€‘ä¸Š
	SpringArm -> TargetArmLength = 400.f; // ä¿®æ”¹æ‚¬è‡‚é•¿åº¦
	SpringArm -> bUsePawnControlRotation = true; // ğŸŒŸè®©æ‚¬è‡‚è·Ÿéš Pawn çš„æ—‹è½¬, ä»¥å®ç°è§’è‰²çš„ä¸Šä¸‹çœ‹ï¼

	//å®ä¾‹åŒ– SpringArm - ğŸ“· æ‘„åƒæœº 
	FollowCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera")); //æ ¹æ® UCameraComponent ç±»åˆ›å»ºå®ä¾‹
	FollowCamera -> SetupAttachment(SpringArm, USpringArmComponent::SocketName); ////å°†ã€æ‘„åƒæœºã€‘é™„ç€åˆ°ã€æ‚¬è‡‚ã€‘ä¸Š, SocketName æ˜¯ USpringArmComponent çš„ä¸€ä¸ªå¸¸é‡, ä»£è¡¨æ‚¬è‡‚çš„æœ«ç«¯
	FollowCamera -> bUsePawnControlRotation = false; // ğŸŒŸè®©æ‘„åƒæœºä¸è·Ÿéš Pawn çš„æ—‹è½¬, é¿å…è§’è‰²çš„ä¸Šä¸‹çœ‹æ—¶, æ•´ä¸ªè§’è‰²éƒ½ä¼šç¿»è½¬é¢å‘åœ°é¢ !!

	//è·å¾—ã€èƒ¶å›Šä½“ã€‘, å¹¶è®¾å®šåˆå§‹å€¼ - ç»‘å®šäººç‰©éª¨éª¼
	GetCapsuleComponent() -> SetCapsuleSize(35.0f, 100.0f); //è®¾ç½®èƒ¶å›Šä½“ã€åŠå¾„ã€‘ã€ã€é«˜åº¦ã€‘ -> å› ä¸ºæ˜¯ä¸ªæŒ‡é’ˆ, æ‰€ä»¥è¦åœ¨ä¸Šé¢ã€å£°æ˜å¤´æ–‡ä»¶ã€‘ï¼ï¼
}

void AMainPlayer::BeginPlay() {
	Super::BeginPlay();
}

void AMainPlayer::Tick(float DeltaTime) { // DeltaTime æ˜¯æ—¶é—´é—´éš”, ç”¨æ¥å¹³è¡¡ä¸åŒè®¾å¤‡çš„å¸§ç‡
	Super::Tick(DeltaTime);
}



// ğŸ‘‡ è‡ªåŠ¨ç”Ÿæˆçš„å‡½æ•°, åœ¨è¿™é‡Œå–æ¥ã€ç»‘å®šã€‘è¾“å…¥çš„è½´æ˜ å°„ (ç¬¬ä¸€æ­¥, ç»‘å®šè½´æ˜ å°„) â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
void AMainPlayer::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) {
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	check(PlayerInputComponent); // æ£€æŸ¥è¾“å…¥æ˜¯å¦æœ‰æ•ˆ, è®°å¾—å¼•å…¥ PlayerInputComponent çš„ .h å¤´æ–‡ä»¶ï¼

	// ğŸ‘‡ ã€åŠ¨ä½œäº‹ä»¶ã€‘
	PlayerInputComponent -> BindAction("Jump", IE_Pressed, this, &AMainPlayer::Jump); // IE_Pressed è¡¨ç¤ºç»‘å®šæŒ‰ä¸‹æŒ‰é”®çš„äº‹ä»¶, Jump æ–¹æ³•ä¸ºå†…ç½®å¥½çš„æ–¹æ³•
	PlayerInputComponent -> BindAction("Jump", IE_Released, this, &ACharacter::StopJumping); // IE_Released è¡¨ç¤ºç»‘å®šæ¾å¼€æŒ‰é”®çš„äº‹ä»¶, StopJumping æ–¹æ³•ä¸ºå†…ç½®å¥½çš„æ–¹æ³•


	// ğŸ‘‡ã€è½´äº‹ä»¶, ä¼šä¸æ–­çš„è°ƒç”¨ã€‘å‰åç§»åŠ¨ç”¨ AMainPlayer, å·¦å³æ—‹è½¬ç”¨ Controller çš„ Yaw, âš ï¸ ä½†æ˜¯ ä¸Šä¸‹æ—‹è½¬ è¦è®©æ‚¬è‡‚ï¼ˆSpringArmï¼‰è¿›è¡Œ Pitch , å¦åˆ™æ•´ä¸ªè§’è‰²éƒ½ä¼šç¿»è½¬é¢å‘åœ°é¢ !!
	PlayerInputComponent -> BindAxis("MoveForward", this, &AMainPlayer::MoveForward); //MoveForward ä¸ºä¸‹æ–¹å£°æ˜çš„å‡½æ•°ï¼ã€è½´æ˜ å°„çš„åç§° - å‰åçœ‹ y è½´ã€‘ã€ã€ç»‘å®šå“ªä¸ªç±»çš„è½´æ˜ å°„(å…¶å®å°±æ˜¯å½“å‰ AMainPlayer è¿™ä¸ªç±»)ã€‘ã€ã€å‡½æ•°çš„æŒ‡é’ˆ(&ç”¨æ¥å–åœ°å€)ã€‘
	PlayerInputComponent -> BindAxis("MoveRight", this, &AMainPlayer::MoveRight); //MoveRight ä¸ºä¸‹æ–¹å£°æ˜çš„å‡½æ•°ï¼ã€è½´æ˜ å°„çš„åç§° - å·¦å³çœ‹ x è½´ã€‘ã€ã€ç»‘å®šå“ªä¸ªç±»çš„è½´æ˜ å°„(å…¶å®å°±æ˜¯å½“å‰ AMainPlayer è¿™ä¸ªç±»)ã€‘ã€ã€å‡½æ•°çš„æŒ‡é’ˆ(&ç”¨æ¥å–åœ°å€)ã€‘

	// ã€è‡ªå·±å®šä¹‰é¼ æ ‡è·Ÿé”®ç›˜è½¬å‘äº‹ä»¶å, è¿™ä¹ˆå†™, ğŸ‘‰è¡¨ç¤ºç”¨ &å–åœ°å€, å¼•ç”¨ AMainPlayer ç±»ä¸­çš„ Turn æ–¹æ³•ï¼ğŸ‘ˆã€‘
	PlayerInputComponent -> BindAxis("Turn", this, &AMainPlayer::Turn); //ã€è½´æ˜ å°„çš„åç§° - å·¦å³çœ‹ z è½´, Yaw Pitchã€‘ã€ã€ç»‘å®šå“ªä¸ªç±»çš„è½´æ˜ å°„(å…¶å®å°±æ˜¯å½“å‰ AMainPlayer è¿™ä¸ªç±»)ã€‘ã€ã€å‡½æ•°çš„æŒ‡é’ˆ(&ç”¨æ¥å–åœ°å€)ã€‘
	PlayerInputComponent -> BindAxis("LookUp", this, &AMainPlayer::LookUp); //ã€è½´æ˜ å°„çš„åç§° - ä¸Šä¸‹çœ‹ z è½´, Yaw Pitchã€‘ã€ã€ç»‘å®šå“ªä¸ªç±»çš„è½´æ˜ å°„(å…¶å®å°±æ˜¯å½“å‰ AMainPlayer è¿™ä¸ªç±»)ã€‘ã€ã€å‡½æ•°çš„æŒ‡é’ˆ(&ç”¨æ¥å–åœ°å€)ã€‘
	PlayerInputComponent -> BindAxis("TurnAtRate", this, &AMainPlayer::TurnAtRate); 
	PlayerInputComponent -> BindAxis("LookUpAtRate", this, &AMainPlayer::LookUpAtRate); 

	// ã€è¿˜æ²¡è‡ªå·±å®šä¹‰é¼ æ ‡è·Ÿé”®ç›˜è½¬å‘äº‹ä»¶æ—¶, è¿™ä¹ˆå†™ã€‘
	// PlayerInputComponent -> BindAxis("Turn", this, &ACharacter::AddControllerYawInput); //ã€è½´æ˜ å°„çš„åç§° - å·¦å³çœ‹ z è½´, Yaw Pitchã€‘ã€ã€ç»‘å®šå“ªä¸ªç±»çš„è½´æ˜ å°„(å…¶å®å°±æ˜¯å½“å‰ AMainPlayer è¿™ä¸ªç±»)ã€‘ã€ã€å‡½æ•°çš„æŒ‡é’ˆ(&ç”¨æ¥å–åœ°å€, ğŸŒŸå¯ä»¥ç»‘å®šçˆ¶ç±»çš„å‡½æ•°ï¼=> &ACharacter::AddControllerYawInput )ã€‘
	// PlayerInputComponent -> BindAxis("LookUp", this, &ACharacter::AddControllerPitchInput); //ã€è½´æ˜ å°„çš„åç§° - ä¸Šä¸‹çœ‹ z è½´, Yaw Pitchã€‘ã€ã€ç»‘å®šå“ªä¸ªç±»çš„è½´æ˜ å°„(å…¶å®å°±æ˜¯å½“å‰ AMainPlayer è¿™ä¸ªç±»)ã€‘ã€ã€å‡½æ•°çš„æŒ‡é’ˆ(&ç”¨æ¥å–åœ°å€, ğŸŒŸå¯ä»¥ç»‘å®šçˆ¶ç±»çš„å‡½æ•°ï¼=> &ACharacter::AddControllerYawInput )ã€‘

	// ã€æ‘„åƒæœºèƒ½å¤Ÿæ—‹è½¬åˆ°è§’è‰²å‰æ–¹ã€‘ , æ›´æ”¹ mainPlayer çš„ Pawn, ç”¨æ¥è®©å¯ä»¥è½¬åˆ°è§’è‰²é¢å‰
	bUseControllerRotationPitch = false;
	bUseControllerRotationRoll = false;
	bUseControllerRotationYaw = false;

	GetCharacterMovement() -> bOrientRotationToMovement = true; //ğŸŒŸè®©è§’è‰²æœç€ç§»åŠ¨çš„æ–¹å‘æ—‹è½¬ ã€UE å†…ç½®çš„æ–¹æ³•, å¯ä»¥åœ¨è“å›¾é‡Œè¾¹çš„ï¼ˆå¥”è·‘è§’è‰²ç§»åŠ¨ï¼‰çœ‹åˆ° ã€‘
	GetCharacterMovement() -> RotationRate = FRotator(0.0f, 540.0f, 0.0f); //ğŸŒŸè®¾ç½®è§’è‰²çš„æ—‹è½¬é€Ÿç‡ ã€UE å†…ç½®çš„æ–¹æ³•, å¯ä»¥åœ¨è“å›¾é‡Œè¾¹çš„ï¼ˆå¥”è·‘è§’è‰²ç§»åŠ¨ï¼‰çœ‹åˆ° ã€‘ => ä¸æ˜¯ä¸€ä¸ªå‡½æ•°, åªæ˜¯ä¸€ä¸ªå˜é‡, æ‰€ä»¥è¦å†™ =

	// è§’è‰²è·³è·ƒçš„å‚æ•°
	GetCharacterMovement() -> JumpZVelocity = 500.0f; // è·³è·ƒé«˜åº¦
	GetCharacterMovement() -> AirControl = 0.15f; // åœ¨ç©ºä¸­çš„ä½ç§»çµæ•åº¦


	BaseTurnRate = 65.0f; // ğŸ”¥å› ä¸ºé”®ç›˜æ¯æ¬¡æŒ‰ä¸‹åªæœ‰ 1 æˆ– -1ï¼Œ æ‰€ä»¥è¦ä¹˜ä»¥ä¸€ä¸ªæ¯”è¾ƒå¤§çš„å€¼, ä¸ç„¶ä¼šæ—‹è½¬å¾—å¾ˆå°
	BaseLookUpRate = 65.0f; // ğŸ”¥å› ä¸ºé”®ç›˜æ¯æ¬¡æŒ‰ä¸‹åªæœ‰ 1 æˆ– -1ï¼Œ æ‰€ä»¥è¦ä¹˜ä»¥ä¸€ä¸ªæ¯”è¾ƒå¤§çš„å€¼, ä¸ç„¶ä¼šæ—‹è½¬å¾—å¾ˆå°
}





// ğŸ‘‡ å‡ ä¸ªè½´æ˜ å°„åŠŸèƒ½ : å‰åå·¦å³ç§»åŠ¨ + ä¸Šä¸‹å·¦å³çœ‹çš„ã€å…·ä½“å®ç°ã€‘(ç¬¬äºŒæ­¥, å…·ä½“å®ç°) , éœ€è¦è€ƒè™‘æ€§èƒ½è·Ÿå®‰å…¨æ€§, å› ä¸ºè½´æ˜ å°„ä¼šä¸€ç›´è¿”å›å€¼, è¦é¿å… Controller ä¸ºç©ºæŒ‡é’ˆæˆ–è€…ä¸€ç›´è¿”å› 0
// ğŸŒŸ è§’è‰²è·³è·ƒåŠŸèƒ½
void AMainPlayer::Jump() {
	Super::Jump(); //ğŸ‘ˆç»§æ‰¿ã€çˆ¶ç±»çš„è·³è·ƒæ–¹æ³•ã€‘
}

// ğŸŒŸ å‰åå¥”è·‘
void AMainPlayer::MoveForward(float Value) {
	// AddMovementInput(GetActorForwardVector(), Value); //ğŸ‘ˆã€ç®€å•ç‰ˆã€‘æ³¨æ„, Pawn ç±»ä¸èƒ½è°ƒç”¨, Characters ç±»æ‰èƒ½è°ƒç”¨ !!  ä¸¤ä¸ªå‚æ•°: ã€å‘ä¸–ç•Œçš„å“ªä¸ªæ–¹å‘ç§»åŠ¨ã€‘ ã€ç§»åŠ¨çš„å€¼ï¼ˆç§»åŠ¨å¤šè¿œï¼‰ã€‘, GetActorForwardVector è¡¨ç¤ºå‘è§’è‰²æ­£é¢æ–¹å‘ç§»åŠ¨

	// ã€ğŸ‘‡å¤æ‚ç‰ˆ - æ‘„åƒæœºèƒ½å¤Ÿæ—‹è½¬åˆ°è§’è‰²å‰æ–¹, å‡ ä½•å­¦ã€‘åˆ©ç”¨æ—‹è½¬çŸ©é˜µè·å– Controller çš„æ—‹è½¬å€¼, ä»è€Œã€è®©æ‘„åƒæœºèƒ½å¤Ÿæ—‹è½¬åˆ°è§’è‰²å‰æ–¹ã€‘
	if((Controller != nullptr) && (Value != 0.0f)) { // nullptr è¡¨ç¤ºç©ºæŒ‡é’ˆ
		FRotator Rotation = Controller -> GetControlRotation();
		FRotator YawRotation(0.0f, Rotation.Yaw, 0.0f); // è¡¨ç¤ºåªå– Yaw è½´çš„å€¼, ä¹Ÿå°±æ˜¯å·¦å³çœ‹çš„å€¼
		FVector Direction = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::X); // è¡¨ç¤ºåªå– X è½´çš„å€¼, ä¹Ÿå°±æ˜¯å‰åçœ‹çš„å€¼ => è·å–æŒ‡å®šè½´çš„å•ä½å‘é‡; EAxis è¡¨ç¤ºæšä¸¾
		AddMovementInput(Direction, Value);
	}
}


// ğŸŒŸ å·¦å³å¥”è·‘
void AMainPlayer::MoveRight(float Value) {
	// AddMovementInput(GetActorRightVector(), Value); //ğŸ‘ˆã€ç®€å•ç‰ˆã€‘æ³¨æ„, Pawn ç±»ä¸èƒ½è°ƒç”¨, Characters ç±»æ‰èƒ½è°ƒç”¨ !!  ä¸¤ä¸ªå‚æ•°: ã€å‘ä¸–ç•Œçš„å“ªä¸ªæ–¹å‘ç§»åŠ¨ã€‘ ã€ç§»åŠ¨çš„å€¼ï¼ˆç§»åŠ¨å¤šè¿œï¼‰ã€‘, GetActorForwardVector è¡¨ç¤ºå‘è§’è‰²æ­£é¢æ–¹å‘ç§»åŠ¨
	// ã€ğŸ‘‡å¤æ‚ç‰ˆ - æ‘„åƒæœºèƒ½å¤Ÿæ—‹è½¬åˆ°è§’è‰²å‰æ–¹, å‡ ä½•å­¦ã€‘åˆ©ç”¨æ—‹è½¬çŸ©é˜µè·å– Controller çš„æ—‹è½¬å€¼, ä»è€Œã€è®©æ‘„åƒæœºèƒ½å¤Ÿæ—‹è½¬åˆ°è§’è‰²å‰æ–¹ã€‘
	if((Controller != nullptr) && (Value != 0.0f)) {
		FRotator Rotation = Controller -> GetControlRotation();
		FRotator YawRotation(0.0f, Rotation.Yaw, 0.0f); // è¡¨ç¤ºåªå– Yaw è½´çš„å€¼, ä¹Ÿå°±æ˜¯å·¦å³çœ‹çš„å€¼
		FVector Direction = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::Y); // è¡¨ç¤ºåªå– X è½´çš„å€¼, ä¹Ÿå°±æ˜¯å‰åçœ‹çš„å€¼ => è·å–æŒ‡å®šè½´çš„å•ä½å‘é‡; EAxis è¡¨ç¤ºæšä¸¾
		AddMovementInput(Direction, Value);
	}
}

// ğŸŒŸ é¼ æ ‡å·¦å³çœ‹
void AMainPlayer::Turn(float Value) {
	if(Value != 0.0f) {
		AddControllerYawInput(Value); 
	}
}


// ğŸŒŸ é¼ æ ‡ä¸Šä¸‹çœ‹
void AMainPlayer::LookUp(float Value) {
	UE_LOG(LogTemp, Warning, TEXT("%f"), Controller -> GetControlRotation().Pitch); // ğŸ‘€ è§‚å¯Ÿä¸‹é¼ æ ‡ä¸Šä¸‹çœ‹çš„å€¼, æ‰“å°åœ¨ã€è¾“å‡ºæ—¥å¿—ã€‘ä¸­, å‘ç°èŒƒå›´æ˜¯ 0/360 ~ 45, 0, 0/360 ~270 è¿™ä¸ªèŒƒå›´æœ€ä½³
	//ğŸ‘‡ä¼šæœ‰ bug, UE å†…éƒ¨æœºåˆ¶, å¿«é€Ÿç›´æ¥æ¨ä¼šæ¨åˆ° 46 åº¦, ç„¶åå°±ä¼šå¡ä½äº†âš ï¸, æ‰€ä»¥è¦ç”¨ä¸‹é¢çš„æ–¹æ³•
	// if((GetControlRotation().Pitch > 270.0f && GetControlRotation().Pitch <= 360.0f) ||
	//   (GetControlRotation().Pitch >= 0.0f && GetControlRotation().Pitch < 45.0f))
	// {...}
	// ğŸ‘‡åˆ¤æ–­éæ³•åŒºåŸŸ, é™åˆ¶ä¸Šä¸‹çœ‹çš„èŒƒå›´
	if(GetControlRotation().Pitch < 270.0f && GetControlRotation().Pitch > 180.0f && Value > 0.0f){  // && Value > 0.0f è¡¨ç¤ºå¦‚æœåœ¨éæ³•åŒºåŸŸ(æ—‹è½¬åˆ°æœ€é¡¶éƒ¨äº†)è¿˜ç»§ç»­è¦å¾€å¤§æ—‹è½¬, åˆ™è¿›è¡Œé˜»æ­¢
		return; 
	}	
	if(GetControlRotation().Pitch > 45.0f && GetControlRotation().Pitch < 180.0f && Value < 0.0f) { // && Value < 0.0f è¡¨ç¤ºå¦‚æœåœ¨éæ³•åŒºåŸŸ(æ—‹è½¬åˆ°æœ€åº•éƒ¨äº†)è¿˜ç»§ç»­è¦å¾€å°æ—‹è½¬, åˆ™è¿›è¡Œé˜»æ­¢
		return;
	}
	//å…¶ä»–åŒºåŸŸåˆ™åˆæ³•, å¯ä»¥ä¸Šä¸‹çœ‹
	AddControllerPitchInput(Value); //é¼ æ ‡ä¸Šä¸‹çœ‹
}


// ğŸŒŸ é”®ç›˜å·¦å³çœ‹çš„å®ç°
void AMainPlayer::TurnAtRate(float KeyboardRate) { // é”®ç›˜ä¸Šä¸‹å·¦å³æ—‹è½¬äº‹ä»¶, æ‰€ä»¥ Rate ä¸æ˜¯ 0 å°±æ˜¯ 1 å°±æ˜¯ -1, æ‰€ä»¥è¦ä¹˜ä»¥ä¸€ä¸ªæ¯”è¾ƒå¤§çš„å€¼, ä¸ç„¶ä¼šæ—‹è½¬å¾—å¾ˆå°
	float Value = KeyboardRate *  BaseTurnRate * GetWorld() -> GetDeltaSeconds(); // ã€BaseTurmRateã€‘ä¸ºğŸ‘†ä¸Šé¢å®šä¹‰çš„å˜é‡, GetWorld().GetDeltaSeconds() è¡¨ç¤ºè·å¾—æ—¶é—´é—´éš” deltaTime, ç”¨æ¥å¹³è¡¡ä¸åŒè®¾å¤‡çš„å¸§ç‡
	if(Value != 0.0f) {
		AddControllerYawInput(Value); // é”®ç›˜å·¦å³çœ‹
	}
}


// ğŸŒŸ é”®ç›˜ä¸Šä¸‹çœ‹çš„å®ç°
void AMainPlayer::LookUpAtRate(float KeyboardRate) { // é”®ç›˜ä¸Šä¸‹å·¦å³æ—‹è½¬äº‹ä»¶, æ‰€ä»¥ Rate ä¸æ˜¯ 0 å°±æ˜¯ 1 å°±æ˜¯ -1, æ‰€ä»¥è¦ä¹˜ä»¥ä¸€ä¸ªæ¯”è¾ƒå¤§çš„å€¼, ä¸ç„¶ä¼šæ—‹è½¬å¾—å¾ˆå°
	float Value = KeyboardRate *  BaseLookUpRate * GetWorld() -> GetDeltaSeconds(); // GetWorld().GetDeltaSeconds() è¡¨ç¤ºè·å¾—æ—¶é—´é—´éš” deltaTime, ç”¨æ¥å¹³è¡¡ä¸åŒè®¾å¤‡çš„å¸§ç‡
	// ğŸ‘‡æ²¡æœ‰é™åˆ¶ä¸Šä¸‹çœ‹èŒƒå›´çš„åšæ³•
	// if(Value != 0.0f) {
	// 	AddControllerPitchInput(-Value); // é”®ç›˜ä¸Šä¸‹çœ‹, -Value æ˜¯å› ä¸ºå®é™…æµ‹è¯•ä¸Šè¦ç›¸å, å¸Œæœ›ä¸‹é”®å¯ä»¥å‘ä¸‹æ—‹è½¬
	// }
	// ğŸ‘‡åˆ¤æ–­éæ³•åŒºåŸŸ, é™åˆ¶ä¸Šä¸‹çœ‹çš„èŒƒå›´
	if(GetControlRotation().Pitch < 270.0f && GetControlRotation().Pitch > 180.0f && Value > 0.0f){  // && Value > 0.0f è¡¨ç¤ºå¦‚æœåœ¨éæ³•åŒºåŸŸ(æ—‹è½¬åˆ°æœ€é¡¶éƒ¨äº†)è¿˜ç»§ç»­è¦å¾€å¤§æ—‹è½¬, åˆ™è¿›è¡Œé˜»æ­¢
		return; 
	}	
	if(GetControlRotation().Pitch > 45.0f && GetControlRotation().Pitch < 180.0f && Value < 0.0f) { // && Value < 0.0f è¡¨ç¤ºå¦‚æœåœ¨éæ³•åŒºåŸŸ(æ—‹è½¬åˆ°æœ€åº•éƒ¨äº†)è¿˜ç»§ç»­è¦å¾€å°æ—‹è½¬, åˆ™è¿›è¡Œé˜»æ­¢
		return;
	}
	AddControllerPitchInput(-Value); // é”®ç›˜ä¸Šä¸‹çœ‹, -Value æ˜¯å› ä¸ºå®é™…æµ‹è¯•ä¸Šè¦ç›¸å, å¸Œæœ›ä¸‹é”®å¯ä»¥å‘ä¸‹æ—‹è½¬
}

